print("Hello world")
print("What is your name")
MyName = input()
print("it good to meet you ,"+ MyName)
print("The length of your name is :")
print(len(MyName))
print("What is your age")
Myage = input()
print("You will be,"+ str(int(Myage)+1)+" in a year")